#!/usr/bin/env bash
# AUTOMATCALLY GENERATED by `shtab`

_shtab_walbot_py_options_='-h --help'
_shtab_walbot_py_commands_='autocomplete autoupdate docs help mexplorer patch restart start startmini stop stopmini suspend test'

_shtab_walbot_py_autocomplete='bash -h --help'
_shtab_walbot_py_autoupdate='-h --help'
_shtab_walbot_py_docs='-h --help -o --out_file'
_shtab_walbot_py_help='-h --help'
_shtab_walbot_py_mexplorer='-h --help'
_shtab_walbot_py_patch='all config.yaml markov.yaml secret.yaml -h --help'
_shtab_walbot_py_restart='-h --help --fast_start --patch --nohup'
_shtab_walbot_py_start='-h --help --autoupdate --fast_start --patch --nohup'
_shtab_walbot_py_startmini='-h --help --fast_start --patch --nohup -m --message'
_shtab_walbot_py_stop='-h --help'
_shtab_walbot_py_stopmini='-h --help --fast_start --patch --nohup'
_shtab_walbot_py_suspend='-h --help --fast_start --patch --nohup -m --message'
_shtab_walbot_py_test='-h --help -v --verbose -vv --verbose2'


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
  compgen -d -S '/' -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -S '/' -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_hyphen() {
  echo $1 | sed 's/-/_/g'
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# $1=COMP_WORDS[1]
_shtab_walbot_py_compgen_root_() {
  local args_gen="_shtab_walbot_py_COMPGEN"
  case "$word" in
    -*) COMPREPLY=( $(compgen -W "$_shtab_walbot_py_options_" -- "$word"; [ -n "${!args_gen}" ] && ${!args_gen} "$word") ) ;;
    *) COMPREPLY=( $(compgen -W "$_shtab_walbot_py_commands_" -- "$word"; [ -n "${!args_gen}" ] && ${!args_gen} "$word") ) ;;
  esac
}

# $1=COMP_WORDS[1]
_shtab_walbot_py_compgen_command_() {
  local flags_list="_shtab_walbot_py_$(_shtab_replace_nonword $1)"
  local args_gen="${flags_list}_COMPGEN"
  COMPREPLY=( $(compgen -W "${!flags_list}" -- "$word"; [ -n "${!args_gen}" ] && ${!args_gen} "$word") )
}

# $1=COMP_WORDS[1]
# $2=COMP_WORDS[2]
_shtab_walbot_py_compgen_subcommand_() {
  local flags_list="_shtab_walbot_py_$(_shtab_replace_nonword "${1}_${2}")"
  local args_gen="${flags_list}_COMPGEN"
  [ -n "${!args_gen}" ] && local opts_more="$(${!args_gen} "$word")"
  local opts="${!flags_list}"
  if [ -z "$opts$opts_more" ]; then
    _shtab_walbot_py_compgen_command_ $1
  else
    COMPREPLY=( $(compgen -W "$opts" -- "$word"; [ -n "$opts_more" ] && echo "$opts_more") )
  fi
}

# Notes:
# `COMPREPLY` contains what will be rendered after completion is triggered
# `word` refers to the current typed word
# `${!var}` is to evaluate the content of `var`
# and expand its content as a variable
#       hello="world"
#       x="hello"
#       ${!x} ->  ${hello} ->  "world"
_shtab_walbot_py() {
  local word="${COMP_WORDS[COMP_CWORD]}"

  COMPREPLY=()

  if [ "${COMP_CWORD}" -eq 1 ]; then
    _shtab_walbot_py_compgen_root_ ${COMP_WORDS[1]}
  elif [ "${COMP_CWORD}" -eq 2 ]; then
    _shtab_walbot_py_compgen_command_ ${COMP_WORDS[1]}
  elif [ "${COMP_CWORD}" -ge 3 ]; then
    _shtab_walbot_py_compgen_subcommand_ ${COMP_WORDS[1]} ${COMP_WORDS[2]}
  fi

  return 0
}

complete -o nospace -F _shtab_walbot_py ./walbot.py
