#!/bin/sh

set -e

function on_exit {
    popd
}

trap on_exit EXIT
pushd `git rev-parse --show-toplevel`

echo "-- Starting linter checks"
echo "-- flake8"
python3 -m flake8 --max-line-length 120 --show-source --exclude venv
echo "-- isort"
python3 -m isort . --check-only --diff
echo "-- Lint check is done"
