name: Nightly

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  pypy-tests:
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - 'pypy3.9'
        - 'pypy3.10'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-extra.txt
        python -m pip install -r tests/requirements.txt
    - name: Run tests
      run: python walbot.py test
  alpine-docker-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -f docker/alpine.Dockerfile -t walbot .
    - name: Run tests in Docker
      run: docker run -i walbot /bin/bash -c "pip install -r tests/requirements.txt && python walbot.py test"
