name: Test coverage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-extra.txt
            tests/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-extra.txt
          python -m pip install -r tests/requirements.txt
      - name: Run tests
        run: python walbot.py test --cov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aobolensk/walbot
