name: Test

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        os-image:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os-image }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r tests/requirements.txt
    - name: Run tests
      run: python walbot.py test
  light-docker-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -f docker/light.Dockerfile -t walbot .
    - name: Run tests in Docker
      run: docker run -i walbot /bin/bash -c "pip install -r tests/requirements.txt && python walbot.py test"
  default-docker-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -f docker/default.Dockerfile -t walbot .
    - name: Run tests in Docker
      run: docker run -i walbot /bin/bash -c "pip install -r tests/requirements.txt && python walbot.py test"
