name: YAML Lint

on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  push:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  workflow_dispatch:

jobs:
  yaml-lint:
    name: Validate YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install yamllint
        run: python3 -m pip install yamllint
      - name: Run yamllint
        run: python3 -m yamllint .
